/* ============================================================
   EQUICRORE — Your personal watchlists
   Extracted from TradingView watchlists R, C, F
   Each symbol links directly to TradingView chart
   ============================================================ */

export interface WatchSymbol {
  sym:      string   // TradingView symbol
  name:     string   // display name
  category: string   // sub-category for grouping
}

export interface WatchCategory {
  id:      string
  label:   string
  flag:    string
  color:   string
  symbols: WatchSymbol[]
}

export const watchCategories: WatchCategory[] = [
  {
    id: 'indices', label: 'Indices', flag: '📊', color: '#7a3ec2',
    symbols: [
      { sym:'NSE:NIFTY',            name:'Nifty 50',              category:'Indian Index' },
      { sym:'NSE:BANKNIFTY',        name:'Bank Nifty',            category:'Indian Index' },
      { sym:'NSE:NIFTY1!',          name:'Nifty Futures',         category:'Indian Futures' },
      { sym:'NSE:BANKNIFTY1!',      name:'Bank Nifty Futures',    category:'Indian Futures' },
      { sym:'NSE:INDIAVIX',         name:'India VIX',             category:'Volatility' },
      { sym:'NSE:SENSEX',           name:'Sensex',                category:'Indian Index' },
      { sym:'NSE:CNXFINANCE',       name:'Nifty Financial Services', category:'Indian Index' },
      { sym:'NSE:NIFTY_MID_SELECT', name:'Nifty Midcap Select',  category:'Indian Index' },
      { sym:'NSE:CNXREALTY',        name:'Nifty Realty',          category:'Indian Sector' },
      { sym:'NSE:CNXMEDIA',         name:'Nifty Media',           category:'Indian Sector' },
      { sym:'NSE:CNXPSUBANK',       name:'Nifty PSU Bank',        category:'Indian Sector' },
      { sym:'NSE:CNXMETAL',         name:'Nifty Metal',           category:'Indian Sector' },
      { sym:'NSE:CNXINFRA',         name:'Nifty Infra',           category:'Indian Sector' },
      { sym:'NSE:CNXCOMMODITIES',   name:'Nifty Commodities',     category:'Indian Sector' },
      { sym:'NSE:CNXSMALLCAP',      name:'Nifty Smallcap',        category:'Indian Index' },
      { sym:'NSE:CNXPHARMA',        name:'Nifty Pharma',          category:'Indian Sector' },
      { sym:'NSE:CNXAUTO',          name:'Nifty Auto',            category:'Indian Sector' },
      { sym:'NSE:CNXIT',            name:'Nifty IT',              category:'Indian Sector' },
      { sym:'NSE:CNXENERGY',        name:'Nifty Energy',          category:'Indian Sector' },
      { sym:'NSE:CNXMIDCAP',        name:'Nifty Midcap',          category:'Indian Index' },
      { sym:'NSE:CNXFMCG',          name:'Nifty FMCG',            category:'Indian Sector' },
      { sym:'NSE:NIFTY_IND_DEFENCE',name:'Nifty Defence',         category:'Indian Sector' },
      { sym:'SP:SPX500',            name:'S&P 500',               category:'US Index' },
      { sym:'DJ:DJI',               name:'Dow Jones',             category:'US Index' },
      { sym:'NASDAQ:NDX',           name:'Nasdaq 100',            category:'US Index' },
      { sym:'CBOE:VIX',             name:'VIX Volatility',        category:'Volatility' },
      { sym:'TVC:US30USD',          name:'US30 (Wall St)',         category:'US Index' },
      { sym:'EUREX:EUSTX50',        name:'Euro Stoxx 50',         category:'European Index' },
      { sym:'EURONEXT:CAC40',       name:'CAC 40 (France)',       category:'European Index' },
      { sym:'XETRA:DAX',            name:'DAX (Germany)',         category:'European Index' },
      { sym:'TVC:NI225',            name:'Nikkei 225 (Japan)',    category:'Asian Index' },
      { sym:'CBOT:YM1!',            name:'Dow Futures (YM)',      category:'US Futures' },
      { sym:'CME:NQ1!',             name:'Nasdaq Futures (NQ)',   category:'US Futures' },
      { sym:'CBOE:VX1!',            name:'VIX Futures',           category:'Volatility' },
      { sym:'TVC:US10Y',            name:'US 10Y Bond Yield',     category:'Bonds' },
    ],
  },
  {
    id: 'indian', label: 'Indian Stocks', flag: '🇮🇳', color: '#009A51',
    symbols: [
      // Banking
      { sym:'NSE:HDFCBANK',    name:'HDFC Bank',           category:'Banking' },
      { sym:'NSE:ICICIBANK',   name:'ICICI Bank',          category:'Banking' },
      { sym:'NSE:AXISBANK',    name:'Axis Bank',           category:'Banking' },
      { sym:'NSE:SBIN',        name:'State Bank of India', category:'Banking' },
      { sym:'NSE:KOTAKBANK',   name:'Kotak Mahindra Bank', category:'Banking' },
      { sym:'NSE:INDUSINDBK',  name:'IndusInd Bank',       category:'Banking' },
      { sym:'NSE:IOB',         name:'Indian Overseas Bank',category:'PSU Bank' },
      { sym:'NSE:PNB',         name:'Punjab National Bank',category:'PSU Bank' },
      { sym:'NSE:UNIONBANK',   name:'Union Bank',          category:'PSU Bank' },
      { sym:'NSE:BANKBARODA',  name:'Bank of Baroda',      category:'PSU Bank' },
      { sym:'NSE:YESBANK',     name:'Yes Bank',            category:'Banking' },
      { sym:'NSE:UCOBANK',     name:'UCO Bank',            category:'PSU Bank' },
      { sym:'NSE:IDFCFIRSTB',  name:'IDFC First Bank',     category:'Banking' },
      { sym:'NSE:FEDERALBNK',  name:'Federal Bank',        category:'Banking' },
      { sym:'NSE:BANDHANBNK',  name:'Bandhan Bank',        category:'Banking' },
      { sym:'NSE:KARURVYSYA',  name:'Karur Vysya Bank',    category:'Banking' },
      // IT
      { sym:'NSE:TCS',         name:'Tata Consultancy',    category:'IT' },
      { sym:'NSE:INFY',        name:'Infosys',             category:'IT' },
      { sym:'NSE:HCLTECH',     name:'HCL Technologies',    category:'IT' },
      { sym:'NSE:WIPRO',       name:'Wipro',               category:'IT' },
      { sym:'NSE:TECHM',       name:'Tech Mahindra',       category:'IT' },
      { sym:'NSE:PERSISTENT',  name:'Persistent Systems',  category:'IT' },
      { sym:'NSE:COFORGE',     name:'Coforge',             category:'IT' },
      { sym:'NSE:TATATECH',    name:'Tata Technologies',   category:'IT' },
      { sym:'NSE:KPITTECH',    name:'KPIT Technologies',   category:'IT' },
      { sym:'NSE:MPHASIS',     name:'Mphasis',             category:'IT' },
      { sym:'NSE:LTTS',        name:'L&T Technology',      category:'IT' },
      { sym:'NSE:OFSS',        name:'Oracle Financial',    category:'IT' },
      { sym:'NSE:BSOFT',       name:'BIRLASOFT',           category:'IT' },
      { sym:'NSE:SONATSOFTW',  name:'Sonata Software',     category:'IT' },
      { sym:'NSE:ZENSARTECH',  name:'Zensar Technologies', category:'IT' },
      { sym:'NSE:HAPPSTMNDS',  name:'Happiest Minds',      category:'IT' },
      { sym:'NSE:TANLA',       name:'Tanla Platforms',     category:'IT' },
      { sym:'NSE:CYIENT',      name:'Cyient',              category:'IT' },
      // Auto
      { sym:'NSE:MARUTI',      name:'Maruti Suzuki',       category:'Auto' },
      { sym:'NSE:TATAMOTORS',  name:'Tata Motors',         category:'Auto' },
      { sym:'NSE:BAJAJ_AUTO',  name:'Bajaj Auto',          category:'Auto' },
      { sym:'NSE:HEROMOTOCO',  name:'Hero MotoCorp',       category:'Auto' },
      { sym:'NSE:EICHERMOT',   name:'Eicher Motors',       category:'Auto' },
      { sym:'NSE:TVSMOTOR',    name:'TVS Motor',           category:'Auto' },
      { sym:'NSE:ASHOKLEY',    name:'Ashok Leyland',       category:'Auto' },
      // Pharma
      { sym:'NSE:SUNPHARMA',   name:'Sun Pharma',          category:'Pharma' },
      { sym:'NSE:DRREDDY',     name:"Dr. Reddy's",         category:'Pharma' },
      { sym:'NSE:CIPLA',       name:'Cipla',               category:'Pharma' },
      { sym:'NSE:LUPIN',       name:'Lupin',               category:'Pharma' },
      { sym:'NSE:AUROPHARMA',  name:'Aurobindo Pharma',    category:'Pharma' },
      { sym:'NSE:APOLLOHOSP',  name:'Apollo Hospitals',    category:'Pharma' },
      { sym:'NSE:ALKEM',       name:'Alkem Laboratories',  category:'Pharma' },
      { sym:'NSE:TORNTPHARM',  name:'Torrent Pharma',      category:'Pharma' },
      { sym:'NSE:GLAND',       name:'Gland Pharma',        category:'Pharma' },
      { sym:'NSE:IPCALAB',     name:'Ipca Laboratories',   category:'Pharma' },
      { sym:'NSE:NATCOPHARM',  name:'Natco Pharma',        category:'Pharma' },
      { sym:'NSE:ZYDUSLIFE',   name:'Zydus Lifesciences',  category:'Pharma' },
      { sym:'NSE:APLLTD',      name:'Alembic Pharma',      category:'Pharma' },
      { sym:'NSE:GRANULES',    name:'Granules India',      category:'Pharma' },
      // Energy & Oil
      { sym:'NSE:RELIANCE',    name:'Reliance Industries', category:'Energy' },
      { sym:'NSE:ONGC',        name:'ONGC',                category:'Energy' },
      { sym:'NSE:IOC',         name:'Indian Oil',          category:'Energy' },
      { sym:'NSE:BPCL',        name:'BPCL',                category:'Energy' },
      { sym:'NSE:COALINDIA',   name:'Coal India',          category:'Energy' },
      { sym:'NSE:PFC',         name:'Power Finance Corp',  category:'Energy' },
      { sym:'NSE:RECLTD',      name:'REC Limited',         category:'Energy' },
      { sym:'NSE:NTPC',        name:'NTPC',                category:'Power' },
      { sym:'NSE:POWERGRID',   name:'Power Grid',          category:'Power' },
      { sym:'NSE:NHPC',        name:'NHPC',                category:'Power' },
      { sym:'NSE:SUZLON',      name:'Suzlon Energy',       category:'Renewable' },
      { sym:'NSE:IREDA',       name:'IREDA',               category:'Renewable' },
      { sym:'NSE:SWSOLAR',     name:'Sterling & Wilson',   category:'Renewable' },
      // Finance & Conglomerates
      { sym:'NSE:BAJFINANCE',  name:'Bajaj Finance',       category:'Finance' },
      { sym:'NSE:BAJAJFINSV',  name:'Bajaj Finserv',       category:'Finance' },
      { sym:'NSE:ADANIENT',    name:'Adani Enterprises',   category:'Conglomerate' },
      { sym:'NSE:ADANIPORTS',  name:'Adani Ports',         category:'Infrastructure' },
      // Metals & Mining
      { sym:'NSE:TATASTEEL',   name:'Tata Steel',          category:'Metals' },
      { sym:'NSE:HINDALCO',    name:'Hindalco',            category:'Metals' },
      { sym:'NSE:JSWSTEEL',    name:'JSW Steel',           category:'Metals' },
      { sym:'NSE:JINDALSTEL',  name:'Jindal Steel',        category:'Metals' },
      { sym:'NSE:NMDC',        name:'NMDC',                category:'Mining' },
      // Cement
      { sym:'NSE:ULTRACEMCO',  name:'UltraTech Cement',   category:'Cement' },
      { sym:'NSE:AMBUJACEM',   name:'Ambuja Cements',     category:'Cement' },
      { sym:'NSE:ACC',         name:'ACC Cement',         category:'Cement' },
      { sym:'NSE:SHREECEM',    name:'Shree Cement',       category:'Cement' },
      // Defence & PSU
      { sym:'NSE:HAL',         name:'Hindustan Aeronautics', category:'Defence' },
      { sym:'NSE:BEL',         name:'Bharat Electronics', category:'Defence' },
      { sym:'NSE:BDL',         name:'Bharat Dynamics',    category:'Defence' },
      { sym:'NSE:GRSE',        name:'GRSE',               category:'Defence' },
      { sym:'NSE:COCHINSHIP',  name:'Cochin Shipyard',    category:'Defence' },
      { sym:'NSE:MAZDOCK',     name:'Mazagon Dock',       category:'Defence' },
      { sym:'NSE:BEML',        name:'BEML',               category:'Defence' },
      { sym:'NSE:BHEL',        name:'BHEL',               category:'PSU' },
      { sym:'NSE:SJVN',        name:'SJVN',               category:'PSU' },
      { sym:'NSE:DATAPATTNS',  name:'Data Patterns',      category:'Defence' },
      { sym:'NSE:ASTRAMICRO',  name:'Astra Microwave',    category:'Defence' },
      { sym:'NSE:SOLARINDS',   name:'Solar Industries',   category:'Defence' },
      // Rail & Infra
      { sym:'NSE:IRFC',        name:'IRFC',               category:'Railways' },
      { sym:'NSE:IRCON',       name:'IRCON',              category:'Railways' },
      { sym:'NSE:RAILTEL',     name:'RailTel',            category:'Railways' },
      { sym:'NSE:RVNL',        name:'RVNL',               category:'Railways' },
      { sym:'NSE:RITES',       name:'RITES',              category:'Railways' },
      { sym:'NSE:IRCTC',       name:'IRCTC',              category:'Railways' },
      { sym:'NSE:NBCC',        name:'NBCC',               category:'Infrastructure' },
      { sym:'NSE:NLCINDIA',    name:'NLC India',          category:'PSU' },
      { sym:'NSE:MRPL',        name:'MRPL',               category:'Energy' },
      // Consumer & Others
      { sym:'NSE:ITC',         name:'ITC',                category:'FMCG' },
      { sym:'NSE:TATACONSUM',  name:'Tata Consumer',      category:'FMCG' },
      { sym:'NSE:ASIANPAINT',  name:'Asian Paints',       category:'Consumer' },
      { sym:'NSE:TITAN',       name:'Titan Company',      category:'Consumer' },
      { sym:'NSE:BHARTIARTL',  name:'Bharti Airtel',      category:'Telecom' },
      { sym:'NSE:DLF',         name:'DLF',                category:'Realty' },
      { sym:'NSE:SOBHA',       name:'Sobha',              category:'Realty' },
      { sym:'NSE:PRESTIGE',    name:'Prestige Estates',   category:'Realty' },
      { sym:'NSE:INDUSTOWER',  name:'Indus Towers',       category:'Telecom' },
      { sym:'NSE:POLYCAB',     name:'Polycab India',      category:'Electricals' },
      { sym:'NSE:SIEMENS',     name:'Siemens India',      category:'Electricals' },
      { sym:'NSE:DIXON',       name:'Dixon Technologies', category:'Electronics' },
      { sym:'NSE:BSE',         name:'BSE Limited',        category:'Finance' },
      { sym:'NSE:PIDILITIND',  name:'Pidilite Industries',category:'Chemicals' },
      { sym:'NSE:SRF',         name:'SRF',                category:'Chemicals' },
      { sym:'NSE:DEEPAKNTR',   name:'Deepak Nitrite',     category:'Chemicals' },
      { sym:'NSE:AARTIIND',    name:'Aarti Industries',   category:'Chemicals' },
      { sym:'NSE:TATACHEM',    name:'Tata Chemicals',     category:'Chemicals' },
      { sym:'NSE:UPL',         name:'UPL',                category:'Agro' },
      { sym:'NSE:COROMANDEL',  name:'Coromandel Intl',   category:'Agro' },
      { sym:'NSE:CHAMBLFERT',  name:'Chambal Fertilizers',category:'Agro' },
      { sym:'NSE:DEEPAKFERT',  name:'Deepak Fertilisers', category:'Agro' },
    ],
  },
  {
    id: 'crypto', label: 'Crypto', flag: '₿', color: '#d39021',
    symbols: [
      { sym:'BINANCE:BTCUSDT',   name:'Bitcoin',          category:'Layer 1' },
      { sym:'BINANCE:ETHUSDT',   name:'Ethereum',         category:'Layer 1' },
      { sym:'BINANCE:BNBUSDT',   name:'BNB',              category:'Layer 1' },
      { sym:'BINANCE:SOLUSD',    name:'Solana',           category:'Layer 1' },
      { sym:'BINANCE:ADAUSDT',   name:'Cardano',          category:'Layer 1' },
      { sym:'BINANCE:AVAXUSDT',  name:'Avalanche',        category:'Layer 1' },
      { sym:'BINANCE:DOTUSDT',   name:'Polkadot',         category:'Layer 1' },
      { sym:'BINANCE:ATOMUSDT',  name:'Cosmos',           category:'Layer 1' },
      { sym:'BINANCE:NEARUSDT',  name:'NEAR Protocol',    category:'Layer 1' },
      { sym:'BINANCE:TRXUSDT',   name:'Tron',             category:'Layer 1' },
      { sym:'BINANCE:XLMUSDT',   name:'Stellar',          category:'Layer 1' },
      { sym:'BINANCE:VETUSDT',   name:'VeChain',          category:'Layer 1' },
      { sym:'BINANCE:ICPUSDT',   name:'Internet Computer',category:'Layer 1' },
      { sym:'BINANCE:FLOWUSDT',  name:'Flow',             category:'Layer 1' },
      { sym:'BINANCE:EGLDUSDT',  name:'MultiversX',       category:'Layer 1' },
      { sym:'BINANCE:XTZUSDT',   name:'Tezos',            category:'Layer 1' },
      { sym:'BINANCE:DOGEUSDT',  name:'Dogecoin',         category:'Meme' },
      { sym:'BINANCE:SHIBUSDT',  name:'Shiba Inu',        category:'Meme' },
      { sym:'BINANCE:PEPEUSDT',  name:'PEPE',             category:'Meme' },
      { sym:'BINANCE:FLOKIUSDT', name:'Floki',            category:'Meme' },
      { sym:'BINANCE:BONKUSDT',  name:'Bonk',             category:'Meme' },
      { sym:'BINANCE:WIFUSDT',   name:'dogwifhat',        category:'Meme' },
      { sym:'BINANCE:TRUMPUSDT', name:'TRUMP',            category:'Meme' },
      { sym:'BINANCE:LINKUSDT',  name:'Chainlink',        category:'DeFi' },
      { sym:'BINANCE:CRVUSDT',   name:'Curve DAO',        category:'DeFi' },
      { sym:'BINANCE:SUSHIUSDT', name:'SushiSwap',        category:'DeFi' },
      { sym:'BINANCE:RUNEUSDT',  name:'THORChain',        category:'DeFi' },
      { sym:'BINANCE:LDOUSDT',   name:'Lido DAO',         category:'DeFi' },
      { sym:'BINANCE:GRTUSDT',   name:'The Graph',        category:'DeFi' },
      { sym:'BINANCE:INJUSDT',   name:'Injective',        category:'DeFi' },
      { sym:'BINANCE:DYDXUSDT',  name:'dYdX',             category:'DeFi' },
      { sym:'BINANCE:1INCHUSDT', name:'1inch',            category:'DeFi' },
      { sym:'BINANCE:ORAIUSDT',  name:'Oraichain',        category:'DeFi' },
      { sym:'BINANCE:AXSUSDT',   name:'Axie Infinity',    category:'Gaming' },
      { sym:'BINANCE:SANDUSDT',  name:'The Sandbox',      category:'Gaming' },
      { sym:'BINANCE:MANAUSDT',  name:'Decentraland',     category:'Gaming' },
      { sym:'BINANCE:GALAUSDT',  name:'Gala',             category:'Gaming' },
      { sym:'BINANCE:ALICEUSDT', name:'My Neighbor Alice',category:'Gaming' },
      { sym:'BINANCE:ENJUSDT',   name:'Enjin Coin',       category:'Gaming' },
      { sym:'BINANCE:CHZUSDT',   name:'Chiliz',           category:'Gaming' },
      { sym:'BINANCE:RENDERUSDT',name:'Render',           category:'AI' },
      { sym:'BINANCE:FETUSDT',   name:'Fetch.ai',         category:'AI' },
      { sym:'BINANCE:TAOUSDT',   name:'Bittensor (TAO)',  category:'AI' },
      { sym:'BINANCE:JUPUSDT',   name:'Jupiter',          category:'Solana Eco' },
      { sym:'BINANCE:STRKUSDT',  name:'Starknet',         category:'Layer 2' },
      { sym:'BINANCE:PNUTUSDT',  name:'Peanut the Squirrel', category:'Meme' },
      { sym:'BINANCE:AUDIOUSDT', name:'Audius',           category:'Other' },
      { sym:'BINANCE:CHRUSDT',   name:'Chromia',          category:'Other' },
      { sym:'BINANCE:PONDUSDT',  name:'Marlin',           category:'Other' },
      { sym:'BINANCE:ROSEUSDT',  name:'Oasis Network',    category:'Other' },
      { sym:'BINANCE:DGBUSDT',   name:'DigiByte',         category:'Other' },
      { sym:'TVC:BTC.D',         name:'BTC Dominance',   category:'Macro' },
    ],
  },
  {
    id: 'forex', label: 'Forex', flag: '💱', color: '#1a73c7',
    symbols: [
      { sym:'FX:EURUSD',  name:'Euro / US Dollar',         category:'Major' },
      { sym:'FX:GBPUSD',  name:'British Pound / USD',      category:'Major' },
      { sym:'FX:USDJPY',  name:'US Dollar / Japanese Yen', category:'Major' },
      { sym:'FX:AUDUSD',  name:'Australian Dollar / USD',  category:'Major' },
      { sym:'FX:USDCAD',  name:'US Dollar / Canadian $',   category:'Major' },
      { sym:'FX:USDCHF',  name:'US Dollar / Swiss Franc',  category:'Major' },
      { sym:'FX:NZDUSD',  name:'New Zealand Dollar / USD', category:'Major' },
      { sym:'FX:GBPJPY',  name:'British Pound / Yen',      category:'Cross' },
      { sym:'FX:EURJPY',  name:'Euro / Japanese Yen',      category:'Cross' },
      { sym:'FX:GBPCAD',  name:'British Pound / CAD',      category:'Cross' },
      { sym:'FX:GBPCHF',  name:'British Pound / CHF',      category:'Cross' },
      { sym:'FX:GBPAUD',  name:'British Pound / AUD',      category:'Cross' },
      { sym:'FX:EURAUD',  name:'Euro / Australian Dollar', category:'Cross' },
      { sym:'FX:EURGBP',  name:'Euro / British Pound',     category:'Cross' },
      { sym:'FX:AUDJPY',  name:'Australian Dollar / Yen',  category:'Cross' },
      { sym:'FX:AUDCAD',  name:'Australian Dollar / CAD',  category:'Cross' },
      { sym:'FX:AUDCHF',  name:'Australian Dollar / CHF',  category:'Cross' },
      { sym:'FX:CADCHF',  name:'Canadian Dollar / CHF',    category:'Cross' },
      { sym:'FX:NZDCHF',  name:'New Zealand Dollar / CHF', category:'Cross' },
      { sym:'NSE:USDINR', name:'USD / Indian Rupee',       category:'India' },
    ],
  },
  {
    id: 'commodities', label: 'Commodities', flag: '🏅', color: '#b98a2e',
    symbols: [
      { sym:'MCX:GOLD1!',        name:'Gold Futures (MCX)',     category:'Precious Metals' },
      { sym:'TVC:XAUUSD',        name:'Gold (Spot)',            category:'Precious Metals' },
      { sym:'MCX:SILVER1!',      name:'Silver Futures (MCX)',   category:'Precious Metals' },
      { sym:'TVC:SILVER',        name:'Silver (Spot)',          category:'Precious Metals' },
      { sym:'TVC:PLATINUM',      name:'Platinum',              category:'Precious Metals' },
      { sym:'MCX:CRUDEOIL1!',    name:'Crude Oil Futures (MCX)',category:'Energy' },
      { sym:'TVC:USOIL',         name:'WTI Crude Oil',         category:'Energy' },
      { sym:'NYMEX:CL1!',        name:'Crude Oil Futures (NYMEX)', category:'Energy' },
      { sym:'MCX:NATURALGAS1!',  name:'Natural Gas (MCX)',      category:'Energy' },
      { sym:'TVC:NATURALGAS',    name:'Natural Gas (Spot)',     category:'Energy' },
    ],
  },
]

// Flat list of all symbols for quick lookup
export const allSymbols = watchCategories.flatMap(c => c.symbols)

// Get TradingView URL for a symbol
export function toTVUrl(tvSym: string): string {
  return `https://in.tradingview.com/chart/?symbol=${encodeURIComponent(tvSym)}`
}
